import Banner from "../components/Banner";
import Header from "../components/Header";
import ProductFeed from "../components/ProductFeed";
import { ToastContainer } from "react-toastify";
import { getSession } from "next-auth/client";
import { useEffect } from "react";
import { db } from "../../firebase";
import Head from "next/head";

export default function Home({ session, products }) {
  useEffect(() => {
    if (session?.user) {
      db.collection("users").doc(session?.user.email).set(
        {
          email: session?.user.email,
          name: session?.user.name,
          photoURL: session?.user.image,
        },
        { merge: true }
      );
    }
  }, [session?.user]);

  return (
    <div className="bg-[#10acd3] dark:bg-gray-800">
      <Head>
        <title>ShopTennis</title>
        <meta name="description" content="Generated by create next app" />
        <link
          rel="icon"
          href="https://res.cloudinary.com/dssvrf9oz/image/upload/v1622372782/image-removebg-preview_20_grp1mc.png"
        />
      </Head>

      <Header />
      <ToastContainer />

      <main className="max-w-screen-2xl mx-auto">
        <Banner />
        <ProductFeed products={products} />
      </main>
    </div>
  );
}

export async function getServerSideProps(context) {
  const session = await getSession(context);
  const allproducts = await db.collection("products").get();

  const products = await Promise.all(
    allproducts.docs.map(async (product) => ({
      id: product.id,
      image: product.data().image,
      category: product.data().category,
      description: product.data().description,
      price: product.data().price,
      title: product.data().title,
      rating: product.data().rating,
    }))
  );

  return { props: { session, products } };
}
